"""Renders the signal library (config/signals.yaml) as Markdown for docs/SIGNAL_LIBRARY.md.

The document is generated from the same configuration the engine runs, so the published
thresholds can never drift from the ones that produce findings.
"""

from typing import Any

from app.analytics.config import AnalyticsConfig, SignalConfig
from app.analytics.scoring import CAPABILITY_LABEL

FAMILIES = [
    (
        "execution_gap",
        "Execution gaps",
        "Declared or expected practice versus what the evidence shows.",
    ),
    ("negative_space", "Negative space", "Evidence that should exist but is missing."),
    ("trend", "Trends", "Change over time against the entity's own baseline."),
    (
        "anomaly",
        "Previously unknown indicators",
        "Behaviour unlike peers that no rule accounts for.",
    ),
]
SEVERITY = {1: "low", 2: "medium", 3: "high", 4: "critical"}


def _value(v: Any) -> str:
    if isinstance(v, float):
        return f"{v:g}"
    return str(v)


def _rule(s: SignalConfig) -> str:
    parts = [f"`{k}` = {_value(v)}" for k, v in s.params.items()]
    parts.append(f"at least {s.min_support} supporting record(s)")
    if s.peer_z_min is not None:
        worse = "above" if s.direction == "high" else "below"
        parts.append(f"and at least {_value(s.peer_z_min)} robust z-scores {worse} peers")
    else:
        parts.append("absolute rule only (no peer condition)")
    return "; ".join(parts)


def signal_library_markdown(cfg: AnalyticsConfig) -> str:
    sc = cfg.scoring
    lines = [
        "# SAT-SA Signal Library",
        "",
        "_Generated by `python -m app.cli signal-docs` from `backend/config/signals.yaml` "
        f"(version {cfg.version}), the configuration the engine runs. Do not edit by hand._",
        "",
        f"{len(cfg.signals)} signals. Each fires only when its absolute rule is met **and**, "
        "where a "
        "peer condition is set, the entity is an outlier against comparable peers (robust "
        "z-score: median and MAD, with a floor on the spread). Every finding records the "
        "metric, the threshold, the peer distribution and the evidence rows behind it. The "
        "SHA-256 of the configuration is stored on each analysis run. Methods are explained in "
        "[`ANALYTICS_METHODOLOGY.md`](ANALYTICS_METHODOLOGY.md).",
        "",
        "## Scoring",
        "",
        "Each finding weighs `w = severity (1-4) x confidence (0-1)`.",
        "",
        f"- **Capability score** (0-100, higher is healthier): "
        f"`S_c = 100 * exp(-sum(w in c) / {_value(sc.capability_k)})`",
        f"- **Supervisory Attention Index** (0-100, higher means review first): "
        f"`SAI = 100 * (1 - exp(-sum_c(weight_c * sum(w in c)) / {_value(sc.sai_k)}))`",
        "",
        "| Capability | SAI weight | Signals |",
        "|---|---|---|",
    ]
    for cap, weight in sorted(sc.capability_weights.items(), key=lambda kv: -kv[1]):
        ids = ", ".join(s.id for s in cfg.signals if s.capability == cap) or "-"
        lines.append(
            f"| {CAPABILITY_LABEL.get(cap, cap).capitalize()} | {_value(weight)} | {ids} |"
        )
    rv = cfg.review
    lines += [
        "",
        f"**Review packs:** the top {rv.top_entities} entities by SAI, plus any entity with SAI "
        f">= {_value(rv.min_sai)}, get a {rv.pack_size}-record pack; {rv.control_share:.0%} of "
        "each pack is a uniform random control sample, so examiners can measure the tool's "
        "hit rate against the background rate.",
        "",
    ]
    for family, title, blurb in FAMILIES:
        signals = [s for s in cfg.signals if s.family == family]
        if not signals:
            continue
        lines += [f"## {title}", "", blurb, ""]
        for s in signals:
            lines += [
                f"### {s.id}: {s.name}",
                "",
                f"*{CAPABILITY_LABEL.get(s.capability, s.capability).capitalize()} · "
                f"severity {s.severity} ({SEVERITY[s.severity]}) · v{s.version}*",
                "",
                f"- **Measures:** {s.description}",
                f"- **Why it matters:** {s.rationale}",
                f"- **Fires when:** {_rule(s)}",
                f"- **Finding text:** {s.narrative.strip()}",
                "",
            ]
    return "\n".join(lines)
