/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + DB check. The frontend polls this to cover Render cold starts.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Log */
        get: operations["audit_log_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Verify */
        get: operations["audit_verify_api_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entities */
        get: operations["list_entities_api_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contract */
        get: operations["contract_api_ingest_contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_ingest_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_ingest_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Json */
        post: operations["ingest_json_api_ingest_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_api_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission */
        get: operations["get_submission_api_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mappings */
        get: operations["list_mappings_api_mappings_get"];
        put?: never;
        /** Create Mapping */
        post: operations["create_mapping_api_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Library */
        get: operations["signal_library_api_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Evaluation */
        get: operations["run_evaluation_api_runs__run_id__evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_api_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Finding */
        get: operations["get_finding_api_findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finding Evidence */
        get: operations["finding_evidence_api_findings__finding_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scores */
        get: operations["scores_api_scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{code}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Profile */
        get: operations["entity_profile_api_entities__code__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packs */
        get: operations["list_packs_api_review_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/packs/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack */
        get: operations["get_pack_api_review_packs__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/packs/{code}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Pack */
        get: operations["export_pack_api_review_packs__code__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Record Outcome */
        patch: operations["record_outcome_api_review_samples__sample_id__patch"];
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage Overview */
        get: operations["coverage_overview_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Coverage */
        get: operations["entity_coverage_api_coverage__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Benchmarks */
        get: operations["benchmarks_api_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends */
        get: operations["trends_api_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback */
        get: operations["list_feedback_api_findings__finding_id__feedback_get"];
        put?: never;
        /** Add Feedback */
        post: operations["add_feedback_api_findings__finding_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validation Summary */
        get: operations["validation_summary_api_validation_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/robustness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Robustness */
        get: operations["robustness_api_validation_robustness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/field": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Field */
        get: operations["field_api_validation_field_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchetypeResult */
        ArchetypeResult: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Severity */
            severity: number;
            /** Planted Signals */
            planted_signals: string[];
            /** Entities */
            entities: number;
            /** Caught */
            caught: number | null;
            /** Flagged */
            flagged: number;
            /** Mean Rank */
            mean_rank: number | null;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditRow"][];
            /** Total */
            total: number;
        };
        /** AuditRow */
        AuditRow: {
            /** Id */
            id: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Object Ref */
            object_ref: string | null;
            /** Payload */
            payload: Record<string, never>;
            /** Hash */
            hash: string;
        };
        /** AuditVerifyResponse */
        AuditVerifyResponse: {
            /** Ok */
            ok: boolean;
            /** Checked */
            checked: number;
            /** First Broken Id */
            first_broken_id?: number | null;
            /** Reason */
            reason?: string | null;
        };
        /** Benchmark */
        Benchmark: {
            /** Run Id */
            run_id: number | null;
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /** Percent */
            percent: boolean;
            /** Median */
            median: number | null;
            /** Features */
            features: components["schemas"]["FeatureInfo"][];
            /** Points */
            points: components["schemas"]["BenchmarkPoint"][];
        };
        /** BenchmarkPoint */
        BenchmarkPoint: {
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Sector */
            sector: string;
            /** Cohort */
            cohort: string;
            /** Rank */
            rank: number | null;
            /** Value */
            value: number;
        };
        /** Body_preview_api_ingest_preview_post */
        Body_preview_api_ingest_preview_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Dataset */
            dataset: string;
        };
        /** Body_upload_api_ingest_upload_post */
        Body_upload_api_ingest_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Dataset */
            dataset: string;
            /**
             * Mapping
             * @description JSON {"canonical_field": "source column"}
             */
            mapping: string;
            /** Entity Code */
            entity_code?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            /**
             * Timezone
             * @default Asia/Kolkata
             */
            timezone: string;
            /** Save Mapping As */
            save_mapping_as?: string | null;
        };
        /** ContractDataset */
        ContractDataset: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Per Entity */
            per_entity: boolean;
            /** Fields */
            fields: components["schemas"]["ContractField"][];
        };
        /** ContractField */
        ContractField: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Required */
            required: boolean;
            /** Description */
            description: string;
            /** Enum */
            enum: string[] | null;
            /** Pseudonymized */
            pseudonymized: boolean;
        };
        /** CoverageCell */
        CoverageCell: {
            /** Asset Type */
            asset_type: string;
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Expected */
            expected: number;
            /** Observed */
            observed: number;
            /** Ratio */
            ratio: number | null;
            /** Missing */
            missing: boolean;
        };
        /** CoverageOverview */
        CoverageOverview: {
            /** Run Id */
            run_id: number | null;
            /** Asset Types */
            asset_types: string[];
            /** Rows */
            rows: components["schemas"]["CoverageRow"][];
        };
        /** CoverageRow */
        CoverageRow: {
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Sector */
            sector: string;
            /** Rank */
            rank: number;
            /** Sai */
            sai: number;
            /** Holes */
            holes: number;
            /** By Asset Type */
            by_asset_type: {
                [key: string]: number | null;
            };
        };
        /** Driver */
        Driver: {
            /** Finding Id */
            finding_id: number;
            /** Signal Id */
            signal_id: string;
            /** Title */
            title: string;
            /** Capability */
            capability: string;
            /** Weight */
            weight: number;
        };
        /** EffortToTarget */
        EffortToTarget: {
            /** Target */
            target: number;
            /** Tool */
            tool: number | null;
            /** Oracle */
            oracle: number | null;
            /** Random */
            random: number | null;
        };
        /** EntityCoverage */
        EntityCoverage: {
            /** Run Id */
            run_id: number;
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Min Expected */
            min_expected: number;
            /** Asset Types */
            asset_types: string[];
            /** Categories */
            categories: string[];
            /** Cells */
            cells: components["schemas"]["CoverageCell"][];
        };
        /** EntityOut */
        EntityOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /** Sector */
            sector: string;
            /** Size Tier */
            size_tier: string;
            /** Soc Model */
            soc_model: string;
            /** Declared 24X7 */
            declared_24x7: boolean;
            /** Submissions */
            submissions: number;
            /** Last Period End */
            last_period_end: string | null;
        };
        /** EntityProfileOut */
        EntityProfileOut: {
            /** Entity Id */
            entity_id: number;
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Sector */
            sector: string;
            /** Size Tier */
            size_tier: string;
            /** Soc Model */
            soc_model: string;
            /** Declared 24X7 */
            declared_24x7: boolean;
            /** Declared Mttr Hours */
            declared_mttr_hours: number | null;
            /** Declared Coverage Pct */
            declared_coverage_pct: number | null;
            /** Run Id */
            run_id: number | null;
            score: components["schemas"]["ScoreOut"] | null;
            /** Peer Capability Median */
            peer_capability_median: {
                [key: string]: number;
            };
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Monthly */
            monthly: components["schemas"]["MonthFeatures"][];
            /** Peer Monthly */
            peer_monthly: components["schemas"]["MonthFeatures"][];
        };
        /** EvaluationBlock */
        EvaluationBlock: {
            /** Signals */
            signals: components["schemas"]["SignalValidation"][];
            /** Weak Entities */
            weak_entities: number;
            /** Weak Caught */
            weak_caught: number;
            /** Healthy Entities */
            healthy_entities: number;
            /** Healthy Flagged */
            healthy_flagged: string[];
            /** Ndcg At 10 */
            ndcg_at_10: number | null;
            /** Precision At 10 */
            precision_at_10: number | null;
            /** Macro Precision */
            macro_precision: number | null;
            /** Macro Recall */
            macro_recall: number | null;
        };
        /** EvaluationOut */
        EvaluationOut: {
            /** Run Id */
            run_id: number;
            /** Signals */
            signals: components["schemas"]["SignalScoreOut"][];
            /** Healthy Entities */
            healthy_entities: number;
            /** Healthy Flagged */
            healthy_flagged: string[];
            /** Weak Entities */
            weak_entities: number;
            /** Weak Caught */
            weak_caught: number;
            /** Ndcg At 10 */
            ndcg_at_10?: number | null;
            /** Precision At 10 */
            precision_at_10?: number | null;
        };
        /** EvidencePage */
        EvidencePage: {
            /** Items */
            items: components["schemas"]["EvidenceRow"][];
            /** Total */
            total: number;
        };
        /** EvidenceRow */
        EvidenceRow: {
            /** Id */
            id: number;
            /** Record Type */
            record_type: string;
            /** Record Id */
            record_id: number | null;
            /** Note */
            note: string | null;
            /** Record */
            record: Record<string, never> | null;
        };
        /** FeatureInfo */
        FeatureInfo: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Percent */
            percent: boolean;
        };
        /** FeedbackIn */
        FeedbackIn: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "accepted" | "rejected" | "needs_info";
            /** Comment */
            comment?: string | null;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Id */
            id: number;
            /** Verdict */
            verdict: string;
            /** Comment */
            comment: string | null;
            /** User */
            user: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeedbackSignal */
        FeedbackSignal: {
            /** Signal Id */
            signal_id: string;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Needs Info */
            needs_info: number;
            /** Precision */
            precision: number | null;
        };
        /** FieldValidation */
        FieldValidation: {
            /** Run Id */
            run_id: number;
            /** Feedback */
            feedback: components["schemas"]["FeedbackSignal"][];
            /** Review */
            review: {
                [key: string]: components["schemas"]["ReviewStratum"];
            };
        };
        /** FindingDetail */
        FindingDetail: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: number;
            /** Entity Id */
            entity_id: number;
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Signal Id */
            signal_id: string;
            /** Family */
            family: string;
            /** Capability */
            capability: string;
            /** Severity */
            severity: number;
            /** Confidence */
            confidence: number;
            /** Metric Value */
            metric_value: number | null;
            /** Peer Percentile */
            peer_percentile: number | null;
            /** Title */
            title: string;
            /** Narrative */
            narrative: string;
            /** Status */
            status: string;
            /** Signal Version */
            signal_version: string;
            /** Details */
            details: Record<string, never>;
            /** Peers */
            peers: components["schemas"]["PeerPoint"][];
            /** Peer Median */
            peer_median: number | null;
            /** Evidence Count */
            evidence_count: number;
        };
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: number;
            /** Entity Id */
            entity_id: number;
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Signal Id */
            signal_id: string;
            /** Family */
            family: string;
            /** Capability */
            capability: string;
            /** Severity */
            severity: number;
            /** Confidence */
            confidence: number;
            /** Metric Value */
            metric_value: number | null;
            /** Peer Percentile */
            peer_percentile: number | null;
            /** Title */
            title: string;
            /** Narrative */
            narrative: string;
            /** Status */
            status: string;
        };
        /** FindingPage */
        FindingPage: {
            /** Items */
            items: components["schemas"]["FindingOut"][];
            /** Total */
            total: number;
            /** Run Id */
            run_id: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
        };
        /** HoldoutResult */
        HoldoutResult: {
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Rank */
            rank: number | null;
            /** Found */
            found: boolean;
            /** Flagged Signals */
            flagged_signals: string[];
            /** Narrative */
            narrative: string | null;
        };
        /**
         * JsonSubmission
         * @description Machine-to-machine submission (the PS's 'APIs where available').
         */
        JsonSubmission: {
            /** Entity Code */
            entity_code: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Timezone
             * @default Asia/Kolkata
             */
            timezone: string;
            /** Datasets */
            datasets: {
                [key: string]: Record<string, never>[];
            };
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MappingIn */
        MappingIn: {
            /** Name */
            name: string;
            /** Dataset */
            dataset: string;
            /** Entity Code */
            entity_code?: string | null;
            /**
             * Source Format
             * @default csv
             */
            source_format: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
        };
        /** MappingOut */
        MappingOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Dataset */
            dataset: string;
            /** Entity Id */
            entity_id: number | null;
            /** Source Format */
            source_format: string;
            /** Mapping Json */
            mapping_json: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MonthFeatures */
        MonthFeatures: {
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Features */
            features: {
                [key: string]: number;
            };
        };
        /** PackDetail */
        PackDetail: {
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Rank */
            rank: number;
            /** Sai */
            sai: number;
            /** Samples */
            samples: number;
            /** Directed */
            directed: number;
            /** Control */
            control: number;
            /** Reviewed */
            reviewed: number;
            /** Confirmed Directed */
            confirmed_directed: number;
            /** Confirmed Control */
            confirmed_control: number;
            /** Run Id */
            run_id: number;
            /** Items */
            items: components["schemas"]["SampleOut"][];
        };
        /** PackSummary */
        PackSummary: {
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Rank */
            rank: number;
            /** Sai */
            sai: number;
            /** Samples */
            samples: number;
            /** Directed */
            directed: number;
            /** Control */
            control: number;
            /** Reviewed */
            reviewed: number;
            /** Confirmed Directed */
            confirmed_directed: number;
            /** Confirmed Control */
            confirmed_control: number;
        };
        /** PeerPoint */
        PeerPoint: {
            /** Entity Code */
            entity_code: string;
            /** Value */
            value: number;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Filename */
            filename: string;
            /** Dataset */
            dataset: string;
            /** Source Format */
            source_format: string;
            /** Sha256 */
            sha256: string;
            /** Row Count */
            row_count: number;
            /** Columns */
            columns: string[];
            /** Sample Rows */
            sample_rows: Record<string, never>[];
            /** Suggested Mapping */
            suggested_mapping: {
                [key: string]: string;
            };
            /** Unmapped Required */
            unmapped_required: string[];
        };
        /** ReviewStratum */
        ReviewStratum: {
            /** Total */
            total: number;
            /** Reviewed */
            reviewed: number;
            /** Confirmed */
            confirmed: number;
            /** Hit Rate */
            hit_rate: number | null;
        };
        /** RobustnessRow */
        RobustnessRow: {
            /** Id */
            id: number;
            /** Batch */
            batch: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Seed */
            seed: number;
            /** Intensity Scale */
            intensity_scale: number;
            /** Config Sha256 */
            config_sha256: string;
            /** Weak Caught */
            weak_caught: number;
            /** Weak Entities */
            weak_entities: number;
            /** Healthy Flagged */
            healthy_flagged: number;
            /** Healthy Entities */
            healthy_entities: number;
            /** Macro Precision */
            macro_precision: number | null;
            /** Macro Recall */
            macro_recall: number | null;
            /** Ndcg At 10 */
            ndcg_at_10: number | null;
            /** Precision At 10 */
            precision_at_10: number | null;
            /** Effort Tool */
            effort_tool: number | null;
            /** Effort Random */
            effort_random: number | null;
            /** Holdout Found */
            holdout_found: number;
            /** Holdout Total */
            holdout_total: number;
        };
        /** RunCreate */
        RunCreate: {
            /** Window Start */
            window_start?: string | null;
            /** Window End */
            window_end?: string | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Triggered By */
            triggered_by: string | null;
            /** Code Version */
            code_version: string;
            /** Config Sha256 */
            config_sha256: string;
            /** Data Sha256 */
            data_sha256: string | null;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /** Progress */
            progress: Record<string, never>;
            /** Error */
            error: string | null;
            /** Findings */
            findings: number;
            /** Findings By Signal */
            findings_by_signal: {
                [key: string]: number;
            };
            /** Entities Flagged */
            entities_flagged: number;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Triggered By */
            triggered_by: string | null;
            /** Code Version */
            code_version: string;
            /** Config Sha256 */
            config_sha256: string;
            /** Data Sha256 */
            data_sha256: string | null;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /** Progress */
            progress: Record<string, never>;
            /** Error */
            error: string | null;
            /** Findings */
            findings: number;
        };
        /** SampleOut */
        SampleOut: {
            /** Id */
            id: number;
            /** Record Type */
            record_type: string;
            /** Record Id */
            record_id: number;
            /** Stratum */
            stratum: string;
            /** Reason */
            reason: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewer */
            reviewer: string | null;
            /** Outcome */
            outcome: string | null;
            /** Record */
            record: Record<string, never> | null;
        };
        /** SampleUpdate */
        SampleUpdate: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "issue_confirmed" | "no_issue" | "needs_info";
        };
        /** ScoreOut */
        ScoreOut: {
            /** Rank */
            rank: number;
            /** Entity Id */
            entity_id: number;
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /** Sector */
            sector: string;
            /** Size Tier */
            size_tier: string;
            /** Soc Model */
            soc_model: string;
            /** Declared 24X7 */
            declared_24x7: boolean;
            /** Sai */
            sai: number;
            /** Capabilities */
            capabilities: {
                [key: string]: number;
            };
            /** Findings */
            findings: number;
            /** Drivers */
            drivers: components["schemas"]["Driver"][];
            /** Summary */
            summary: string;
        };
        /** ScorePage */
        ScorePage: {
            /** Run Id */
            run_id: number | null;
            /** Window Start */
            window_start: string | null;
            /** Window End */
            window_end: string | null;
            /** Formula */
            formula: Record<string, never>;
            /** Items */
            items: components["schemas"]["ScoreOut"][];
        };
        /** SignalLibrary */
        SignalLibrary: {
            /** Config Version */
            config_version: string;
            /** Config Sha256 */
            config_sha256: string;
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
        };
        /** SignalOut */
        SignalOut: {
            /** Id */
            id: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /** Family */
            family: string;
            /** Capability */
            capability: string;
            /** Severity */
            severity: number;
            /** Direction */
            direction: string;
            /** Peer Z Min */
            peer_z_min: number | null;
            /** Min Support */
            min_support: number;
            /** Min Scale */
            min_scale: number | null;
            /** Params */
            params: Record<string, never>;
            /** Description */
            description: string;
            /** Rationale */
            rationale: string;
        };
        /** SignalScoreOut */
        SignalScoreOut: {
            /** Signal Id */
            signal_id: string;
            /** Planted */
            planted: number;
            /** Flagged */
            flagged: number;
            /** True Pos */
            true_pos: number;
            /** Precision */
            precision: number | null;
            /** Recall */
            recall: number | null;
            /** False Pos */
            false_pos: string[];
            /** Missed */
            missed: string[];
        };
        /** SignalValidation */
        SignalValidation: {
            /** Signal Id */
            signal_id: string;
            /** Planted */
            planted: number;
            /** Flagged */
            flagged: number;
            /** True Pos */
            true_pos: number;
            /** Precision */
            precision: number | null;
            /** Recall */
            recall: number | null;
            /** False Pos */
            false_pos: string[];
            /** Missed */
            missed: string[];
        };
        /** SubmissionDetail */
        SubmissionDetail: {
            /** Id */
            id: number;
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Source Format */
            source_format: string;
            /** Status */
            status: string;
            /** Row Counts */
            row_counts: {
                [key: string]: number;
            };
            /** Errors */
            errors: number;
            /** Warnings */
            warnings: number;
            /** File Sha256 */
            file_sha256: string | null;
            /** Dq Report */
            dq_report: Record<string, never>;
        };
        /** SubmissionPage */
        SubmissionPage: {
            /** Items */
            items: components["schemas"]["SubmissionSummary"][];
            /** Total */
            total: number;
        };
        /** SubmissionSummary */
        SubmissionSummary: {
            /** Id */
            id: number;
            /** Entity Code */
            entity_code: string;
            /** Entity Name */
            entity_name: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Source Format */
            source_format: string;
            /** Status */
            status: string;
            /** Row Counts */
            row_counts: {
                [key: string]: number;
            };
            /** Errors */
            errors: number;
            /** Warnings */
            warnings: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** TrendSeries */
        TrendSeries: {
            /** Entity Code */
            entity_code: string;
            /** Values */
            values: (number | null)[];
        };
        /** Trends */
        Trends: {
            /** Run Id */
            run_id: number | null;
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /** Percent */
            percent: boolean;
            /** Periods */
            periods: string[];
            /** Median */
            median: (number | null)[];
            /** Series */
            series: components["schemas"]["TrendSeries"][];
        };
        /** UploadResult */
        UploadResult: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "submission" | "entity_profile";
            submission?: components["schemas"]["SubmissionDetail"] | null;
            /**
             * Entity Codes
             * @default []
             */
            entity_codes: string[];
            /** Profile Report */
            profile_report?: Record<string, never> | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationSummary */
        ValidationSummary: {
            /** Run Id */
            run_id: number;
            evaluation: components["schemas"]["EvaluationBlock"];
            yield_curves: components["schemas"]["YieldCurves"];
            /** Archetypes */
            archetypes: components["schemas"]["ArchetypeResult"][];
            /** Holdout */
            holdout: components["schemas"]["HoldoutResult"][];
        };
        /** YieldCurves */
        YieldCurves: {
            /** K */
            k: number[];
            /** Tool */
            tool: number[];
            /** Oracle */
            oracle: number[];
            /** Random Mean */
            random_mean: number[];
            /** Random P05 */
            random_p05: number[];
            /** Random P95 */
            random_p95: number[];
            effort_to_target?: components["schemas"]["EffortToTarget"] | null;
            /**
             * N Entities
             * @default 0
             */
            n_entities: number;
            /**
             * N Weak
             * @default 0
             */
            n_weak: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    audit_log_api_audit_get: {
        parameters: {
            query?: {
                action?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_verify_api_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_entities_api_entities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"][];
                };
            };
        };
    };
    contract_api_ingest_contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDataset"][];
                };
            };
        };
    };
    preview_api_ingest_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_api_ingest_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_ingest_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_ingest_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_json_api_ingest_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submissions_api_submissions_get: {
        parameters: {
            query?: {
                entity_code?: string | null;
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_api_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mappings_api_mappings_get: {
        parameters: {
            query?: {
                dataset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mapping_api_mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_library_api_signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalLibrary"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evaluation_api_runs__run_id__evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_findings_get: {
        parameters: {
            query?: {
                run_id?: number | null;
                entity_code?: string | null;
                signal_id?: string | null;
                family?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_finding_api_findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_evidence_api_findings__finding_id__evidence_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                finding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scores_api_scores_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_profile_api_entities__code__profile_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packs_api_review_packs_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pack_api_review_packs__code__get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_pack_api_review_packs__code__export_csv_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_outcome_api_review_samples__sample_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_overview_api_coverage_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_coverage_api_coverage__code__get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityCoverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    benchmarks_api_benchmarks_get: {
        parameters: {
            query?: {
                feature?: string;
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Benchmark"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_trends_get: {
        parameters: {
            query?: {
                feature?: string;
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trends"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_api_findings__finding_id__feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_feedback_api_findings__finding_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validation_summary_api_validation_summary_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    robustness_api_validation_robustness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobustnessRow"][];
                };
            };
        };
    };
    field_api_validation_field_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldValidation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
