"""initial schema

Revision ID: 4f3555207642
Revises:
Create Date: 2026-09-28 20:17:07.407321
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4f3555207642"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("data_sha256", sa.String(length=64), nullable=True),
        sa.Column("params_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_run")),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("pw_hash", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("username", name=op.f("uq_app_user_username")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("object_ref", sa.String(length=128), nullable=True),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        sa.UniqueConstraint("hash", name=op.f("uq_audit_log_hash")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_table(
        "entity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("sector", sa.String(length=32), nullable=False),
        sa.Column("size_tier", sa.String(length=16), nullable=False),
        sa.Column("soc_model", sa.String(length=16), nullable=False),
        sa.Column("declared_24x7", sa.Boolean(), nullable=False),
        sa.Column("declared_sla_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("declared_mttr_hours", sa.Float(), nullable=True),
        sa.Column("declared_coverage_pct", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity")),
        sa.UniqueConstraint("code", name=op.f("uq_entity_code")),
    )
    op.create_index(op.f("ix_entity_sector"), "entity", ["sector"], unique=False)
    op.create_table(
        "asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("asset_ref_hash", sa.String(length=64), nullable=False),
        sa.Column("asset_type", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=8), nullable=False),
        sa.Column("criticality", sa.SmallInteger(), nullable=False),
        sa.Column("expected_sources", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entity.id"], name=op.f("fk_asset_entity_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset")),
        sa.UniqueConstraint("entity_id", "asset_ref_hash", name=op.f("uq_asset_entity_id")),
    )
    op.create_index(op.f("ix_asset_entity_id"), "asset", ["entity_id"], unique=False)
    op.create_table(
        "column_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("dataset", sa.String(length=32), nullable=False),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("mapping_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_column_mapping_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_mapping")),
    )
    op.create_table(
        "entity_period_feature",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("feature_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_entity_period_feature_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_run.id"],
            name=op.f("fk_entity_period_feature_run_id_analysis_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "entity_id", "period", name=op.f("pk_entity_period_feature")
        ),
    )
    op.create_table(
        "entity_score",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column(
            "capability_scores_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("sai", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_entity_score_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_run.id"],
            name=op.f("fk_entity_score_run_id_analysis_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", "entity_id", "period", name=op.f("pk_entity_score")),
    )
    op.create_table(
        "finding",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.Date(), nullable=True),
        sa.Column("signal_id", sa.String(length=16), nullable=False),
        sa.Column("signal_version", sa.String(length=16), nullable=False),
        sa.Column("family", sa.String(length=24), nullable=False),
        sa.Column("capability", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("peer_percentile", sa.Float(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("details_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_finding_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_run.id"],
            name=op.f("fk_finding_run_id_analysis_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding")),
    )
    op.create_index("ix_finding_run_entity", "finding", ["run_id", "entity_id"], unique=False)
    op.create_index(op.f("ix_finding_signal_id"), "finding", ["signal_id"], unique=False)
    op.create_table(
        "review_sample",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("record_type", sa.String(length=16), nullable=False),
        sa.Column("record_id", sa.BigInteger(), nullable=False),
        sa.Column("stratum", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_review_sample_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_run.id"],
            name=op.f("fk_review_sample_run_id_analysis_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_sample")),
    )
    op.create_index(op.f("ix_review_sample_run_id"), "review_sample", ["run_id"], unique=False)
    op.create_table(
        "submission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=True),
        sa.Column("row_counts_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dq_report_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_submission_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission")),
    )
    op.create_index(op.f("ix_submission_entity_id"), "submission", ["entity_id"], unique=False)
    op.create_table(
        "synthetic_truth",
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("archetype", sa.String(length=32), nullable=False),
        sa.Column("planted_signals", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_synthetic_truth_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_synthetic_truth")),
    )
    op.create_table(
        "case_record",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("assignee_hash", sa.String(length=64), nullable=True),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("escalation_level", sa.String(length=16), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("root_cause", sa.String(length=128), nullable=True),
        sa.Column("remediation_action", sa.String(length=128), nullable=True),
        sa.Column("reopened_count", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_case_record_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
            name=op.f("fk_case_record_submission_id_submission"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_record")),
        sa.UniqueConstraint("entity_id", "source_ref", name=op.f("uq_case_record_entity_id")),
    )
    op.create_index(
        "ix_case_record_entity_closed", "case_record", ["entity_id", "closed_at"], unique=False
    )
    op.create_table(
        "finding_evidence",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("finding_id", sa.BigInteger(), nullable=False),
        sa.Column("record_type", sa.String(length=16), nullable=False),
        sa.Column("record_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_finding_evidence_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_evidence")),
    )
    op.create_index(
        op.f("ix_finding_evidence_finding_id"), "finding_evidence", ["finding_id"], unique=False
    )
    op.create_table(
        "source_volume",
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("source_tool", sa.String(length=16), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
            name=op.f("fk_source_volume_asset_id_asset"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_source_volume_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "entity_id", "asset_id", "source_tool", "day", name=op.f("pk_source_volume")
        ),
    )
    op.create_table(
        "supervisor_feedback",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("finding_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_supervisor_feedback_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_supervisor_feedback_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supervisor_feedback")),
    )
    op.create_index(
        op.f("ix_supervisor_feedback_finding_id"),
        "supervisor_feedback",
        ["finding_id"],
        unique=False,
    )
    op.create_table(
        "alert",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=True),
        sa.Column("source_ref", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("asset_ref_hash", sa.String(length=64), nullable=True),
        sa.Column("case_ref", sa.String(length=64), nullable=True),
        sa.Column("source_tool", sa.String(length=16), nullable=False),
        sa.Column("rule_ref", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=48), nullable=False),
        sa.Column("mitre_tactic", sa.String(length=48), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disposition", sa.String(length=16), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=True),
        sa.Column("analyst_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["asset.id"], name=op.f("fk_alert_asset_id_asset"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_record.id"],
            name=op.f("fk_alert_case_id_case_record"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entity.id"], name=op.f("fk_alert_entity_id_entity"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
            name=op.f("fk_alert_submission_id_submission"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert")),
        sa.UniqueConstraint("entity_id", "source_ref", name=op.f("uq_alert_entity_id")),
    )
    op.create_index(op.f("ix_alert_asset_id"), "alert", ["asset_id"], unique=False)
    op.create_index(op.f("ix_alert_case_id"), "alert", ["case_id"], unique=False)
    op.create_index("ix_alert_entity_created", "alert", ["entity_id", "created_at"], unique=False)
    op.create_index(
        "ix_alert_entity_severity_closed",
        "alert",
        ["entity_id", "severity", "closed_at"],
        unique=False,
    )
    op.create_table(
        "case_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("actor_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_record.id"],
            name=op.f("fk_case_event_case_id_case_record"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_event")),
        sa.UniqueConstraint("case_id", "ts", "action", name=op.f("uq_case_event_case_id")),
    )
    op.create_index(op.f("ix_case_event_case_id"), "case_event", ["case_id"], unique=False)
    op.create_table(
        "escalation",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("from_tier", sa.String(length=16), nullable=False),
        sa.Column("to_tier", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_record.id"],
            name=op.f("fk_escalation_case_id_case_record"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
            name=op.f("fk_escalation_entity_id_entity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escalation")),
        sa.UniqueConstraint("case_id", "ts", "to_tier", name=op.f("uq_escalation_case_id")),
    )
    op.create_index(op.f("ix_escalation_case_id"), "escalation", ["case_id"], unique=False)
    op.create_index(op.f("ix_escalation_entity_id"), "escalation", ["entity_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_escalation_entity_id"), table_name="escalation")
    op.drop_index(op.f("ix_escalation_case_id"), table_name="escalation")
    op.drop_table("escalation")
    op.drop_index(op.f("ix_case_event_case_id"), table_name="case_event")
    op.drop_table("case_event")
    op.drop_index("ix_alert_entity_severity_closed", table_name="alert")
    op.drop_index("ix_alert_entity_created", table_name="alert")
    op.drop_index(op.f("ix_alert_case_id"), table_name="alert")
    op.drop_index(op.f("ix_alert_asset_id"), table_name="alert")
    op.drop_table("alert")
    op.drop_index(op.f("ix_supervisor_feedback_finding_id"), table_name="supervisor_feedback")
    op.drop_table("supervisor_feedback")
    op.drop_table("source_volume")
    op.drop_index(op.f("ix_finding_evidence_finding_id"), table_name="finding_evidence")
    op.drop_table("finding_evidence")
    op.drop_index("ix_case_record_entity_closed", table_name="case_record")
    op.drop_table("case_record")
    op.drop_table("synthetic_truth")
    op.drop_index(op.f("ix_submission_entity_id"), table_name="submission")
    op.drop_table("submission")
    op.drop_index(op.f("ix_review_sample_run_id"), table_name="review_sample")
    op.drop_table("review_sample")
    op.drop_index(op.f("ix_finding_signal_id"), table_name="finding")
    op.drop_index("ix_finding_run_entity", table_name="finding")
    op.drop_table("finding")
    op.drop_table("entity_score")
    op.drop_table("entity_period_feature")
    op.drop_table("column_mapping")
    op.drop_index(op.f("ix_asset_entity_id"), table_name="asset")
    op.drop_table("asset")
    op.drop_index(op.f("ix_entity_sector"), table_name="entity")
    op.drop_table("entity")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("app_user")
    op.drop_table("analysis_run")
    # ### end Alembic commands ###
