"""validation study

Revision ID: 18252a840b98
Revises: 0d42ebe1ea2a
Create Date: 2026-09-29 10:55:58.325217
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "18252a840b98"
down_revision: str | None = "0d42ebe1ea2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_study",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch", sa.String(length=32), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("intensity_scale", sa.Float(), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("results_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_study")),
    )
    op.create_index(op.f("ix_validation_study_batch"), "validation_study", ["batch"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_validation_study_batch"), table_name="validation_study")
    op.drop_table("validation_study")
    # ### end Alembic commands ###
