"""run summary

Revision ID: f381d3464998
Revises: 4f3555207642
Create Date: 2026-09-28 20:36:55.109470
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f381d3464998"
down_revision: str | None = "4f3555207642"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_run",
        sa.Column(
            "summary_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),  # existing runs get an empty summary
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_run", "summary_json")
    # ### end Alembic commands ###
