"""entity score drivers

Revision ID: 0d42ebe1ea2a
Revises: f381d3464998
Create Date: 2026-09-28 21:04:12.964341
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0d42ebe1ea2a"
down_revision: str | None = "f381d3464998"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "entity_score",
        sa.Column(
            "drivers_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),  # existing scores get empty drivers
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity_score", "drivers_json")
    # ### end Alembic commands ###
